olimpiadas = {
    "OBMEP": {
        "categoria": "Exatas",
        "abreviacao": "OBMEP",
        "link": "http://www.obmep.org.br/",
        "olimpiada": "Olimpíada Brasileira de Matemática das Escolas Públicas",
        "logo": "https://www.colegioicj.com.br/wp-content/uploads/2023/08/5040.jpg",
        "modo": "preencher",
        "dataInicial": "5/2/2025",
        "dataFinal": "17/03/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBMEP Mirim": {
        "categoria": "Exatas",
        "abreviacao": "OBMEP Mirim",
        "link": "https://olimpiadamirim.obmep.org.br/?_gl=1*1wrivkv*_ga*MjA0Nzk1NDAyNS4xNzQ0OTk0NTI4*_ga_21HEQ7CQ8K*MTc0NDk5NDUyOC4xLjAuMTc0NDk5NDUyOC4wLjAuMA..",
        "olimpiada": "Olimpíada Brasileira de Matemática das Escolas Públicas - Mirim",
        "logo": "https://www.colegioicj.com.br/wp-content/uploads/2023/08/5040.jpg",
        "modo": "preencher",
        "dataInicial": "30/04/2025",
        "dataFinal": "10/6/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": False,
        "ensinoMedio": False,
        "livre": False,
        "ensinoSuperior": False
    },
    "Canguru de Matemática": {
        "categoria": "Exatas",
        "abreviacao": "Canguru de Matemática",
        "link": "https://www.cangurudematematicabrasil.com.br/",
        "olimpiada": "Olimpíada Canguru de Matemática Brasil",
        "logo": "https://www.bosquemananciais.org.br/media/images/Canguru%20de%20Matem%C3%A1tica(1).png",
        "modo": "preencher",
        "dataInicial": "7/11/2024",
        "dataFinal": "14/03/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Mandacaru de Matemática": {
        "categoria": "Exatas",
        "abreviacao": "Mandacaru de Matemática",
        "link": "https://olimpiadamandacaru.com.br",
        "olimpiada": "Olimpíada Mandacaru de Matemática",
        "logo": "https://yt3.googleusercontent.com/a_Vv2JKKFuhw-mTPWkTZFpMtdQvEOpPQo28BAnn4N7fAwg3GFXsD9hjzwi_Y9O0_eh0KvRZwoA=s900-c-k-c0x00ffffff-no-rj",
        "modo": "preencher",
        "dataInicial": "1/2/2025",
        "dataFinal": "10/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBM": {
        "categoria": "Exatas",
        "abreviacao": "OBM",
        "link": "https://www.obm.org.br/",
        "olimpiada": "Olimpíada Brasileira de Matemática",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2013/03/0.gif",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "TM²": {
        "categoria": "Exatas",
        "abreviacao": "TM²",
        "link": "https://www.tm2.org.br/",
        "olimpiada": "Torneio Meninas na Matemática",
        "logo": "https://www.tm2.org.br/content/themes/tm2/img/favicon.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OMU": {
        "categoria": "Exatas",
        "abreviacao": "OMU",
        "link": "https://www.olimpiada.ime.unicamp.br/",
        "olimpiada": "Olimpíada de Matemática da Unicamp",
        "logo": "https://www.olimpiada.ime.unicamp.br/img/logo_omu.svg",
        "modo": "preencher",
        "dataInicial": "28/10/2025",
        "dataFinal": "10/4/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBMF": {
        "categoria": "Exatas",
        "abreviacao": "OBMF",
        "link": "https://www.seletaeducacao.com.br/obmf",
        "olimpiada": "Olimpíada Brasileira de Matemática Financeira",
        "logo": "https://ifsp.edu.br/images/2024/02_fevereiro/Polos_Olimpicos/16-OBMF.png",
        "modo": "preencher",
        "dataInicial": "",
        "dataFinal": "21/05/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OMPD": {
        "categoria": "Exatas",
        "abreviacao": "OMPD",
        "link": "https://matematicopordiversao.wordpress.com/",
        "olimpiada": "Olimpíada Matemáticos por Diversão",
        "logo": "https://matematicopordiversao.wordpress.com/wp-content/uploads/2021/09/logo-ompd-copia.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "OBRL": {
        "categoria": "Exatas",
        "abreviacao": "OBRL",
        "link": "https://www.obrl.com.br/",
        "olimpiada": "Olimpíada Brasileira de Raciocínio Lógico",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2018/10/7.png",
        "modo": "preencher",
        "dataInicial": "1/3/2025",
        "dataFinal": "5/9/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "IMC": {
        "categoria": "Exatas",
        "abreviacao": "IMC",
        "link": "https://www.alphalumen.org.br/olimpiada-internacional-de-matematica-e-do-conhecimento/",
        "olimpiada": "Olimpíada Internacional de Matemática e do Conhecimento",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr2AK8pB1WNj5zuu_7ZZV1p7WJQIwrB0hOdQ&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "MSF": {
        "categoria": "Exatas",
        "abreviacao": "MSF",
        "link": "https://www.matematicasemfronteiras.org/",
        "olimpiada": "Olimpíada Internacional Matemática Sem Fronteiras",
        "logo": "https://sp-ao.shortpixel.ai/client/to_webp,q_lossless,ret_img,w_1024,h_700/https://www.farroupilha.g12.br/novo/wp-content/uploads/2024/04/miniatura-site_OIMSF_2024.jpg",
        "modo": "preencher",
        "dataInicial": "",
        "dataFinal": "17/05/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "AMO": {
        "categoria": "Exatas",
        "abreviacao": "AMO",
        "link": "https://olimpiadasinternacionais.org/amo/",
        "olimpiada": "Olimpíada de Matemática das Américas",
        "logo": "https://olympiadindia.in/wp-content/uploads/2024/05/AMO_logo__400_x_300_px_-removebg-preview.png",
        "modo": "manter",
        "dataInicial": "",
        "dataFinal": "10/10/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TIMO": {
        "categoria": "Exatas",
        "abreviacao": "TIMO",
        "link": "https://olimpiadasinternacionais.org/timo/",
        "olimpiada": "Olimpíada Internacional de Matemática da Tailândia",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHqyttA6NhkBc5CDqm8u4ibFjCUTLYbRT9KQ&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "WMTC": {
        "categoria": "Exatas",
        "abreviacao": "WMTC",
        "link": "https://wmtc.international/",
        "olimpiada": "World Mathematics Team Competition",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr5qwebqPvb1TgxLObJfWbs59kCqqy5ubKEA&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OSM": {
        "categoria": "Exatas",
        "abreviacao": "OSM",
        "link": "https://www.osmsertao.com.br/",
        "olimpiada": "Olimpíada Sertaneja de Matemática",
        "logo": "https://extensao.ufcg.edu.br/images/OSM.png",
        "modo": "manter",
        "dataInicial": "26/03/2025",
        "dataFinal": "30/05/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OIM": {
        "categoria": "Exatas",
        "abreviacao": "OIM",
        "link": "https://olimpiadaitabirana.com.br/",
        "olimpiada": "Olimpíada Itabirana de Matemática",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeLQwjptUFPhv3j8KczHTgJMbHN7gMGqYW4g&s",
        "modo": "preencher",
        "dataInicial": "8/4/2025",
        "dataFinal": "20/06/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OMASP": {
        "categoria": "Exatas",
        "abreviacao": "OMASP",
        "link": "https://olimpiadassp.educacao.sp.gov.br/omasp/#:~:text=A%20Olimp%C3%ADada%20de%20Matem%C3%A1tica%20do,o%20fascinante%20mundo%20da%20matem%C3%A1tica.",
        "olimpiada": "Olimpíada de Matemática do Estado de São Paulo",
        "logo": "https://img.cmswebsg.com.br/atanews.com.br/image?src=https://atanews.com.br/images/noticias/70474/capa_25beac7afe51996a7.png.png&w=800&h=600&output=webp",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBOM": {
        "categoria": "Exatas",
        "abreviacao": "OBOM",
        "link": "https://noic.com.br/obo/matematica/",
        "olimpiada": "Olimpíada Brasileira Online de Matemática",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2023/08/IMG-20230801-WA0008.jpg?ssl=1",
        "modo": "manter",
        "dataInicial": "3/8/2025",
        "dataFinal": "9/9/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Copa Multilaser": {
        "categoria": "Exatas",
        "abreviacao": "Copa Multilaser",
        "link": "http://www.copamultilaser.com.br/",
        "olimpiada": "Copa Multilaser",
        "logo": "https://noic.com.br/wp-content/uploads/2018/10/Logo_copa-multilaser.jpg",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Tubarão de Matemática": {
        "categoria": "Exatas",
        "abreviacao": "Tubarão de Matemática",
        "link": "http://tubaraodematematica.com.br/",
        "olimpiada": "Tubarão de Matemática",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2018/10/tubar%C3%A3o.jpg",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OMIF": {
        "categoria": "Exatas",
        "abreviacao": "OMIF",
        "link": "https://omif.com.br/",
        "olimpiada": "Olimpíada de Matemática das Instituições Federais",
        "logo": "https://omif.com.br/images/favicon.png",
        "modo": "manter",
        "dataInicial": "1/3/2025",
        "dataFinal": "20/04/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBSAT": {
        "categoria": "Tecnologia",
        "abreviacao": "OBSAT",
        "link": "https://www.obsat.org.br/",
        "olimpiada": "Olimpíada Brasileira de Satélites MCTI",
        "logo": "https://www.obsat.org.br/img/Logotipo_cinza_letrapreta.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "OBT": {
        "categoria": "Tecnologia",
        "abreviacao": "OBT",
        "link": "https://www.alphalumen.org.br/olimpiada-brasileira-de-tecnologia-obt/amp/",
        "olimpiada": "Olimpíada Brasileira de Tecnologia",
        "logo": "https://www.alphalumen.org.br/wp-content/uploads/2021/08/logoobt.png",
        "modo": "manter",
        "dataInicial": "16/08/2025",
        "dataFinal": "28/09/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBI": {
        "categoria": "Tecnologia",
        "abreviacao": "OBI",
        "link": "https://olimpiada.ic.unicamp.br/",
        "olimpiada": "Olimpíada Brasileira de Informática",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpRC0iuP1XUI3YZlVf-Dg6dv4YYSRdkGgiGg&s",
        "modo": "preencher",
        "dataInicial": "6/3/2025",
        "dataFinal": "11/9/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "CoRA": {
        "categoria": "Tecnologia",
        "abreviacao": "CoRA",
        "link": "http://cora.cpdee.ufmg.br/#",
        "olimpiada": "Competição de Robôs Autônomos",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjYIeLV3NQcUuzWZ3oPMae9y9kTzFoEFInZQ&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "TFC": {
        "categoria": "Tecnologia",
        "abreviacao": "TFC",
        "link": "https://tfcbr.inf.ufsm.br/olimpiadas/computacao-tfc",
        "olimpiada": "Torneio Feminino de Computação",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2023/07/tfclogo.png?ssl=1",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBR": {
        "categoria": "Tecnologia",
        "abreviacao": "OBR",
        "link": "https://obr.robocup.org.br/",
        "olimpiada": "Olimpíada Brasileira de Robótica",
        "logo": "https://www.cp2.g12.br/blog/niteroi/files/2021/11/logo-obr-720p.png",
        "modo": "manter",
        "dataInicial": "10/3/2025",
        "dataFinal": "1/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBAFOG": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBAFOG",
        "link": "http://www.oba.org.br/site/",
        "olimpiada": "Olimpíada Brasileira de Foguetes",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC0mwH4W_NGlxDyi-EuktK9WzJp6V9MxZCzA&s",
        "modo": "manter",
        "dataInicial": "15/02/2025",
        "dataFinal": "1/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TJR": {
        "categoria": "Tecnologia",
        "abreviacao": "TJR",
        "link": "https://www.torneiojrobotica.org/",
        "olimpiada": "Torneio Juvenil de Robótica",
        "logo": "https://www.torneiojrobotica.org/gallery_gen/0f3ba5a07b38eb63028278b0ee2e738e_fit.png?ts=1743544943",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Bebras": {
        "categoria": "Tecnologia",
        "abreviacao": "Bebras",
        "link": "https://www.bebrasbrasil.com.br/",
        "olimpiada": "Competição Internacional de Pensamento Computacional",
        "logo": "https://scontent.fcpq17-1.fna.fbcdn.net/v/t39.30808-6/454722748_475523018571053_3022125897902412000_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=YFXGFT2yM7oQ7kNvwE87v0_&_nc_oc=AdkYheb1X4ng27dHhFZBurCa6T9JnD6rh0jnhJRMcuh_rQbZd5JFiGmoS1H6xLNNdKTU-Hx3efu8aaP1xb2c9joi&_nc_zt=23&_nc_ht=scontent.fcpq17-1.fna&_nc_gid=zzQob9MpSKjD55FR_CLZPQ&oh=00_AfEoPIvrxx1uRiwZvH30B9IAqIuHISk4M12O2hy4Da3Kcg&oe=681B11EE",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "ONDA": {
        "categoria": "Tecnologia",
        "abreviacao": "ONDA",
        "link": "https://olimpiadaonda.com/",
        "olimpiada": "Olimpíada Nacional de Aplicativos",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ84w1dN7uh4XSsdKPrVKfWb4ncrcGmio8f4Q&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBOI": {
        "categoria": "Tecnologia",
        "abreviacao": "OBOI",
        "link": "https://noic.com.br/obo/informatica/",
        "olimpiada": "Olimpíada Brasileira Online de Informática",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2023/07/Copia-de-.OBOI-3-copy.png?fit=431%2C158&ssl=1",
        "modo": "manter",
        "dataInicial": "3/6/2025",
        "dataFinal": "3/8/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "First LEGO League": {
        "categoria": "Tecnologia",
        "abreviacao": "First LEGO League",
        "link": "https://www.firstlegoleague.org/",
        "olimpiada": "First LEGO League",
        "logo": "https://yt3.googleusercontent.com/NGmdzU7LNgBBh8jPunr5DN6oHUtDUOM1o9UNGzhEyfjSiDpoGqvLXyVakqHFdd69CozfUm3T=s900-c-k-c0x00ffffff-no-rj",
        "modo": "manter",
        "dataInicial": "",
        "dataFinal": "18/04/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "First Tech Challenge": {
        "categoria": "Tecnologia",
        "abreviacao": "First Tech Challenge",
        "link": "https://www.portaldaindustria.com.br/sesi/canais/torneio-de-robotica/first-tech-challenge-brasil/",
        "olimpiada": "First Tech Challenge",
        "logo": "https://sesisc.org.br/sites/default/files/inline-images/Torneio-Robotica-FLL-logo.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "F1 in Schools": {
        "categoria": "Tecnologia",
        "abreviacao": "F1 in Schools",
        "link": "http://f1inschoolsbrazil.com.br/",
        "olimpiada": "F1 in Schools",
        "logo": "https://www.f1inschools.co.uk/uploads/1/1/8/9/118908723/editor/f1-rm-in-schools-stk-positive-standard.png?1676565060",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "WRO": {
        "categoria": "Tecnologia",
        "abreviacao": "WRO",
        "link": "https://wrobr.com.br/",
        "olimpiada": "World Robotics Olympiad",
        "logo": "https://yt3.googleusercontent.com/aoY6neOBuxttl6dVCniY6HGuNb0VKTeN5i-eRgQEhC5wSuzCXbLDD74OyIQdhQiIejsBk8vk_A=s900-c-k-c0x00ffffff-no-rj",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TBR": {
        "categoria": "Tecnologia",
        "abreviacao": "TBR",
        "link": "https://www.torneiobrasilderobotica.com.br/",
        "olimpiada": "Torneio Brasil de Robótica",
        "logo": "https://yt3.googleusercontent.com/ytc/AIdro_mbl0_v46q2YyMgOenfyJda2MOaGleM2rme2raBywx99G4=s900-c-k-c0x00ffffff-no-rj",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBA": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBA",
        "link": "http://www.oba.org.br/site/",
        "olimpiada": "Olimpíada Brasileira de Astronomia e Astronáutica",
        "logo": "https://static.wixstatic.com/media/796bbb_feb7d2f23d4944b583fa3ad9afac2de3~mv2.png/v1/fill/w_568,h_340,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/796bbb_feb7d2f23d4944b583fa3ad9afac2de3~mv2.png",
        "modo": "manter",
        "dataInicial": "15/02/2025",
        "dataFinal": "1/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBF": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBF",
        "link": "https://www1.fisica.org.br/olimpiada/2024/",
        "olimpiada": "Olimpíada Brasileira de Física",
        "logo": "https://bkpsitecpsnew.blob.core.windows.net/uploadsitecps/sites/1/2008/11/obf.jpg",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBQ",
        "link": "https://www.obquimica.org/olimpiadas/index/olimpiada-brasileira-de-quimica",
        "olimpiada": "Olimpíada Brasileira de Química",
        "logo": "https://obquimica.org/public/site/public/posts/1471956857_f11.jpg",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBQ Jr.": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBQ Jr.",
        "link": "https://www.obquimica.org/olimpiadas/index/olimpiada-brasileira-de-quimica-junior",
        "olimpiada": "Olimpíada Brasileira de Química Júnior",
        "logo": "https://ampulhetadosaber.com/wp-content/uploads/2019/06/OBQjr-900x900.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": False,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBFEP": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBFEP",
        "link": "https://www1.fisica.org.br/~obfep/",
        "olimpiada": "Olimpíada Brasileira de Física das Escolas Públicas",
        "logo": "https://noic.com.br/wp-content/uploads/2013/05/logo-obfep.png",
        "modo": "preencher",
        "dataInicial": "1/3/2025",
        "dataFinal": "31/05/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TVQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "TVQ",
        "link": "https://sites.google.com/unicamp.br/torneio-virtual-de-quimica",
        "olimpiada": "Torneio Virtual de Química",
        "logo": "https://colegiomonforte.com.br/images/olimpiadas/tvq-torneio-virtual-de-quimica.png",
        "modo": "preencher",
        "dataInicial": "7/4/2025",
        "dataFinal": "11/5/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Camaleão da Química": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Camaleão da Química",
        "link": "https://sites.google.com/view/olimpiadacamaleao?usp=sharing",
        "olimpiada": "Olimpíada Camaleão da Química",
        "logo": "https://images.even3.com/FsCR3LKv_XhLROCHONLRuDo9hp8=/fit-in/250x250/smart/https://static.even3.com/logos/LOGO.88da6c5d30594fd9915e.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "IYPT": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "IYPT",
        "link": "https://www.iyptbrasil.com/sobre-o-torneio",
        "olimpiada": "Torneio Brasileiro de Jovens Físicos",
        "logo": "https://lh4.googleusercontent.com/proxy/HjqzhgGCDmklXGzQvhuOPLdsDVsy-QJb_6S5zWZj_O2msxvLfeOGprI81FE0y36kuZhln26iKQ46gSNHlvikzN8G4sMZfpP0x9SbN5Vf3jrz1H8M",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OVF": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OVF",
        "link": "https://www.villaloboseducacao.com.br/olimpiada-virtual-de-fisica-2024-ovf/",
        "olimpiada": "Olimpíada Virtual de Física",
        "logo": "https://www.villaloboseducacao.com.br/wp-content/uploads/2023/09/Design-sem-nome-23.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TFEM": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "TFEM",
        "link": "https://tfcbr.inf.ufsm.br/fisica",
        "olimpiada": "Torneio de Física para Meninas",
        "logo": "https://www.ifsp.edu.br/images/2024/02_fevereiro/Polos_Olimpicos/7-TFisicaMeninas.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TNF": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "TNF",
        "link": "https://www.seletaeducacao.com.br/tnf",
        "olimpiada": "Torneio Nacional de Física",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcg8Qg9ooEnDkzKRmZoP3pVDI2B7m9QpcpUA&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBSMA": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBSMA",
        "link": "https://olimpiada.fiocruz.br/",
        "olimpiada": "Olimpíada Brasileira de Saúde e Meio Ambiente",
        "logo": "https://www.fiocruzbrasilia.fiocruz.br/wp-content/uploads/2023/07/logo.png",
        "modo": "manter",
        "dataInicial": "",
        "dataFinal": "",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBB": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBB",
        "link": "https://olimpiadasdebiologia.butantan.gov.br/",
        "olimpiada": "Olimpíada Brasileira de Biologia",
        "logo": "https://olimpiadascientificas.org/static/images/obb.png",
        "modo": "manter",
        "dataInicial": "27/01/2025",
        "dataFinal": "27/02/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OMED": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OMED",
        "link": "https://www.omed.online/",
        "olimpiada": "Olimpíada de Medicina",
        "logo": "https://static.wixstatic.com/media/962d59_d42bb4c8cfd945a49e10613a45aa6cc8~mv2.png/v1/fill/w_206,h_206,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Design%20sem%20nome.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": False,
        "livre": False,
        "ensinoSuperior": True
    },
    "Brain Bee": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Brain Bee",
        "link": "https://brazilianbrainbee.org/",
        "olimpiada": "Olimpíada Brasileira de Neurociências",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDp5m09011E9x0e43-MWHJNNRlt79uZY6zWg&s",
        "modo": "manter",
        "dataInicial": "1/2/2025",
        "dataFinal": "5/5/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": False
    },
    "SynBio": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "SynBio",
        "link": "https://olimpiadadebiologiasintetica.org/",
        "olimpiada": "Olimpíada Brasileira de Biologia Sintética",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkC-PqMlZ_rrGVSqRlZ_sl3mWTp1UDH17Fkg&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "TNBio": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "TNBio",
        "link": "https://www.seletaeducacao.com.br/tnbio",
        "olimpiada": "Torneio Nacional de Biologia",
        "logo": "https://ifsp.edu.br/images/2024/02_fevereiro/Polos_Olimpicos/8-TorneioNBiologia.png",
        "modo": "preencher",
        "dataInicial": "8/1/2025",
        "dataFinal": "20/08/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBBT": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBBT",
        "link": "https://www.obbiotec.com.br/",
        "olimpiada": "Olimpíada Brasileira de Biotecnologia",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEb5yMOKWfN3w7nAKJNLQ71Ntz5FTNHg_vTg&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "ONEE": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "ONEE",
        "link": "https://www.onee.org.br/",
        "olimpiada": "Olimpíada Nacional de Eficiência Energética",
        "logo": "https://mobtex-sites.s3.amazonaws.com/c2_gZtPwBs1bm1fwhkv6V828171891390066748b6cbc45c_b4699ba7b6c690a51711c61bbee9c7bd.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": False,
        "livre": False,
        "ensinoSuperior": False
    },
    "ONC": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "ONC",
        "link": "https://www.onciencias.org/",
        "olimpiada": "Olimpíada Nacional de Ciências",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuufcm70pi5o_XRSLs7kcq5j_hRf9k_kxVPg&s",
        "modo": "manter",
        "dataInicial": "1/4/2025",
        "dataFinal": "12/8/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBC": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBC",
        "link": "http://www.obciencias.com.br/",
        "olimpiada": "Olimpíada Brasileira de Ciências",
        "logo": "https://lh6.googleusercontent.com/proxy/C8WmdXrZjtSmo-BEuaMeDwjqnGrbxlclb2cgycbYEZGNtOFBsFFQ72wFK78XJ-EyHwvlgIcrZO8nZ8IpzzfUuozzatyYAKzVie0hZdzfNYXh2lNNg8Xb",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "24/04/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBO": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBO",
        "link": "https://olimpiada.maredeciencia.eco.br/",
        "olimpiada": "Olimpíada Brasileira do Oceano",
        "logo": "https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/noticias/2022/03/olimpiada-brasileira-do-oceano-movimenta-estudantes-em-torno-do-tema/logo-preferencial.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Restaura Natureza": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Restaura Natureza",
        "link": "https://restauranatureza.org.br/",
        "olimpiada": "Olimpíada Brasileira de Restauração de Ecossistemas",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnJ1zA95wPRLjdb0FIk3F_DHa66i7twd-6ThXj_pi1F275NNnhBaFEeD89Qw2n3iz-pXw&usqp=CAU",
        "modo": "preencher",
        "dataInicial": "4/2/2025",
        "dataFinal": "5/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "ClimateScience": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "ClimateScience",
        "link": "https://climatescience.org/ptBR/olympiad",
        "olimpiada": "Olimpíada ClimateScience",
        "logo": "https://climatescience.org/ptBR/climate-science/icons/climate-science-icon-192x192.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBAP": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBAP",
        "link": "https://obap.ifsuldeminas.edu.br",
        "olimpiada": "Olimpíada Brasileira de Agropecuária",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJZKonEvOj4lS_5f7l4m1dMF-EcP3-RtTsCQ&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "ONAD": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "ONAD",
        "link": "https://www.onad.com.br/ONADBRASIL/index.html",
        "olimpiada": "Olimpíada Nacional de Astronomia Digital",
        "logo": "https://www2.ifal.edu.br/campus/satuba/noticias/abertas-inscricoes-para-1a-olimpiada-nacional-de-astronomia-digital/onad-olimpiada-astronomia-digital.jpg/@@images/a0d67f24-bf42-4eba-aa73-d280649e32b9.jpeg",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OMV": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OMV",
        "link": "https://olimpiadademedicina.org/",
        "olimpiada": "Olimpíada de Medicina Vitalis",
        "logo": "https://fractal-public-assets.s3-sa-east-1.amazonaws.com/img/logo_vitalis.svg",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "Quimeninas": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Quimeninas",
        "link": "https://quimeninas.obquimica.org/",
        "olimpiada": "Quimeninas",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSxiZ-iOX7EHP8XE5UwFmIYrQ7HFiuRoUJhA&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBOQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBOQ",
        "link": "https://noic.com.br/obo/quimica/",
        "olimpiada": "Olimpíada Brasileira Online de Química",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2024/04/OBOQ_.png?resize=431%2C158&ssl=1",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBOF": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBOF",
        "link": "https://noic.com.br/obo/fisica/",
        "olimpiada": "Olimpíada Brasileira Online de Física",
        "logo": "https://media.licdn.com/dms/image/v2/D4D0BAQF1JyJtipWRYA/company-logo_200_200/company-logo_200_200/0/1690133599530?e=2147483647&v=beta&t=jOW7ZT3usy4CxSz11R6gfE5IHRRUTXmkwQx4YeIiTI0",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBB Virtual": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBB Virtual",
        "link": "https://olimpiadasdebiologia.butantan.gov.br/",
        "olimpiada": "Olimpíada Brasileira de Biologia Virtual",
        "logo": "https://static.wixstatic.com/media/a3451f_9db7e40539f342bd8bc2ff6d9f179b14~mv2.png/v1/crop/x_16,y_0,w_303,h_303/fill/w_196,h_196,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/a3451f_9db7e40539f342bd8bc2ff6d9f179b14~mv2.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBOA": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OBOA",
        "link": "https://noic.com.br/obo/astronomia/",
        "olimpiada": "Olimpíada Brasileira Online de Astronomia",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9r3V1dhrIOHqus9h0d3TsVg1s63iEsvW7Ng&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "ONNQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "ONNQ",
        "link": "https://obquimica.org/olimpiadas/index/olimpiada-norte-nordeste-de-quimica",
        "olimpiada": "Olimpíada Norte-Nordeste de Química",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6wvWx-wNFIKu9sMB-NgoQYnP-D_6gXCd59ghQJIDmz7gJnuZe",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "CNQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "CNQ",
        "link": "https://ampulhetadosaber.com/quimica/cnq/",
        "olimpiada": "Campeonato Nacional de Química",
        "logo": "https://ampulhetadosaber.com/wp-content/uploads/2023/03/CNQ-logo-293x300.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "LASC": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "LASC",
        "link": "https://www.lasc.space/",
        "olimpiada": "Latin American Space Challenge",
        "logo": "https://yt3.googleusercontent.com/ytc/AIdro_nq_apZHCSbJkgCsb-AEcTPWyFOHqgp0-aP7ahF0uzo4w=s900-c-k-c0x00ffffff-no-rj",
        "modo": "manter",
        "dataInicial": "25/03/2025",
        "dataFinal": "8/4/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "Copa Americanense de Foguetes": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Copa Americanense de Foguetes",
        "link": "http://www.amerifog.com.br/",
        "olimpiada": "Copa Americanense de Foguetes",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVAIBvPNh1BKjXahu0JRuWiKjqOv-_9MX4HQ&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "IAAC": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "IAAC",
        "link": "https://iaac.space/pt/",
        "olimpiada": "International Astronomy and Astrophysics Competition",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ02uBFoaPu5OQFFUNKSKUuQ1lw1Wn5eBcXEg&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "4/7/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
            "ensinoSuperior": True
    },
    "Olimpíada Polar On": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "Olimpíada Polar On",
        "link": "https://proex.uergs.edu.br/moocs/curso-polaron",
        "olimpiada": "Olimpíada Polar On",
        "logo": "https://www.uergs.edu.br/upload/recortes/201912/20114900_95362_GDO.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OMQ": {
        "categoria": "Ciências da Natureza",
        "abreviacao": "OMQ",
        "link": "https://omq.qui.ufmg.br/",
        "olimpiada": "Olimpíada Mineira de Química",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPojT_IWc3G4Z1loEHgBd_pM7SV0SoQCPw-w&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "ONHB": {
        "categoria": "Humanas",
        "abreviacao": "ONHB",
        "link": "https://www.olimpiadadehistoria.com.br/",
        "olimpiada": "Olimpíada Nacional em História do Brasil",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuk80BDyUPMkiM_UWPYP5Wtz2sGBxf1MujbQ&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "ONHB Aberta": {
        "categoria": "Humanas",
        "abreviacao": "ONHB Aberta",
        "link": "https://www.olimpiadadehistoria.com.br/",
        "olimpiada": "Olimpíada Nacional de História do Brasil Aberta Para Todos",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAr5pT4FmtxGlu_T-cbEP2fAK-BB8v-y0-bw&s",
        "modo": "preencher",
        "dataInicial": "3/2/2025",
        "dataFinal": "25/04/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBG": {
        "categoria": "Humanas",
        "abreviacao": "OBG",
        "link": "https://obgeografia.com.br/",
        "olimpiada": "Olimpíada Brasileira de Geografia",
        "logo": "https://www.unifal-mg.edu.br/obgeografia/wp-content/uploads/sites/191/2021/02/circulo-cor-300x300.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBC": {
        "categoria": "Humanas",
        "abreviacao": "OBC",
        "link": "https://olimpiadadecartografia.uff.br/",
        "olimpiada": "Olimpíada Brasileira de Cartografia",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFpsy8Ev82NZktAYJaI59Ignwje2vEiPw9Mw&s",
        "modo": "manter",
        "dataInicial": "24/03/2025",
        "dataFinal": "3/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBGP": {
        "categoria": "Humanas",
        "abreviacao": "OBGP",
        "link": "https://www.seletaeducacao.com.br/obgp",
        "olimpiada": "Olimpíada Brasileira de GeoPolítica",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZntHZLuO09J3ZKzabpbHOvZFDLEa-2eh2MQ&s",
        "modo": "manter",
        "dataInicial": "8/1/2025",
        "dataFinal": "30/04/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBCH": {
        "categoria": "Humanas",
        "abreviacao": "OBCH",
        "link": "http://www.obch.com.br/",
        "olimpiada": "Olimpíada Brasileira de Ciências Humanas",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrqCkZy3gtyVwb-oHsahy6-J5ukMh7jqlUGw&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "ONFIL": {
        "categoria": "Humanas",
        "abreviacao": "ONFIL",
        "link": "https://onfilbr.org/",
        "olimpiada": "Olimpíada Nacional de Filosofia",
        "logo": "https://onfilbr.org/wp-content/uploads/2024/03/Onfil-Positivo.png",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": True
    },
    "OBOCH": {
        "categoria": "Humanas",
        "abreviacao": "OBOCH",
        "link": "https://noic.com.br/obo/humanas/",
        "olimpiada": "Olimpíada Brasileira Online de Ciências Humanas",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2024/04/oboch.jpg?ssl=1",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBL": {
        "categoria": "Linguagens",
        "abreviacao": "OBL",
        "link": "https://obling.org/",
        "olimpiada": "Olimpíada Brasileira de Linguística",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2018/04/obl_logo.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "2/6/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBOL": {
        "categoria": "Linguagens",
        "abreviacao": "OBOL",
        "link": "https://noic.com.br/obo/linguistica/",
        "olimpiada": "Olimpíada Brasileira Online de Linguística",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2024/07/obol_logo.jpg?resize=431%2C236&ssl=1",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBLI": {
        "categoria": "Linguagens",
        "abreviacao": "OBLI",
        "link": "https://www.seletaeducacao.com.br/obli",
        "olimpiada": "Olimpíada Brasileira de Língua Inglesa",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4FHwiquZkiTBomk6qkEUfL4i42ZV8sS8sg&s",
        "modo": "manter",
        "dataInicial": "8/1/2025",
        "dataFinal": "11/6/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OP": {
        "categoria": "Linguagens",
        "abreviacao": "OP",
        "link": "https://olimpiadadeportugues.org/",
        "olimpiada": "Olimpíada de Português",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOO5zKRNkSb09xITEv3xbw9YYTa5vZhb4Ajw&s",
        "modo": "preencher",
        "dataInicial": "20/01/2025",
        "dataFinal": "9/5/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OP bê-á-bá": {
        "categoria": "Linguagens",
        "abreviacao": "OP bê-á-bá",
        "link": "https://olimpiadadeportugues.org/3a-op-be-a-ba",
        "olimpiada": "Olimpíada de Português bê-á-bá",
        "logo": "https://olimpiadadeportugues.org/images/site/ilustras/ilustra11-min.webp",
        "modo": "manter",
        "dataInicial": "18/03/2025",
        "dataFinal": "3/9/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": False,
        "ensinoMedio": False,
        "livre": False,
        "ensinoSuperior": False
    },
    "OL": {
        "categoria": "Linguagens",
        "abreviacao": "OL",
        "link": "https://www.olimpiadadeliteratura.com.br/",
        "olimpiada": "Olimpíada de Literatura",
        "logo": "https://s1.static.brasilescola.uol.com.br/be/2025/02/banner-olimpiada-literatura.jpg",
        "modo": "preencher",
        "dataInicial": "6/2/2025",
        "dataFinal": "28/04/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBS": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBS",
        "link": "https://obssaberes.org/",
        "olimpiada": "Olimpíada Brasileira do Saber",
        "logo": "https://bkpsitecpsnew.blob.core.windows.net/uploadsitecps/sites/1/2023/09/obs-logo-2023.jpg",
        "modo": "preencher",
        "dataInicial": "2/1/2025",
        "dataFinal": "12/3/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBECON": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBECON",
        "link": "https://obecon.org/",
        "olimpiada": "Olimpíada Brasileira de Economia",
        "logo": "https://i0.wp.com/noic.com.br/wp-content/uploads/2020/05/OBECON_LOGO_2020.png?resize=640%2C148&ssl=1",
        "modo": "manter",
        "dataInicial": "17/03/2025",
        "dataFinal": "6/4/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "OBInvest": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBInvest",
        "link": "https://obinvest.org/",
        "olimpiada": "Olimpíada Brasileira de Investimentos",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQedw_9ndBOhxCwqId9VpJ2UPNdk0WOGD4UVA&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": False,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBEF": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBEF",
        "link": "https://www.ufpb.br/educacaofinanceira",
        "olimpiada": "Olimpíada Brasileira de Educação Financeira",
        "logo": "https://ifrs.edu.br/caxias/wp-content/uploads/sites/8/2024/07/PHOTO-2024-06-27-07-48-44.jpg",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "Olitef": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "Olitef",
        "link": "https://www.olitef.com.br/",
        "olimpiada": "Olimpíada do Tesouro Direto de Educação Financeira",
        "logo": "https://olitef.com.br/wp-content/uploads/2024/05/image_saiba_mais.png",
        "modo": "manter",
        "dataInicial": "19/03/2025",
        "dataFinal": "1/9/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    },
    "DNA": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "DNA",
        "link": "http://www.desafionacional.com.br/dna_em/index.html",
        "olimpiada": "Desafio Nacional Acadêmico",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKr4jyZ2djov0EFJGgHgx3ws1mBgP98tUZjQ&s",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBICT": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBICT",
        "link": "https://www.obict.com.br/",
        "olimpiada": "Olimpíada Brasileira de Inovação, Ciência e Tecnologia",
        "logo": "https://www.obict.com.br/assets/images/index-meta.png",
        "modo": "manter",
        "dataInicial": "2/3/2025",
        "dataFinal": "14/04/2025",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": True,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OF": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OF",
        "link": "https://olimpiadadofuturo.com.br/",
        "olimpiada": "Olimpíada do Futuro - Sapientia",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gTvjnrrIoESAHMGOlc1o0syqTR_eG1VgvA&s",
        "modo": "preencher",
        "dataInicial": "N/A",
        "dataFinal": "N/A",
        "inscriçãoEscola": False,
        "inscriçãoAluno": True,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": True,
        "ensinoSuperior": True
    },
    "OBEMP": {
        "categoria": "Interdisciplinares e outros",
        "abreviacao": "OBEMP",
        "link": "https://obempreende.com.br/",
        "olimpiada": "Olimpíada Brasileira de Empreendedorismo",
        "logo": "https://images.sympla.com.br/640103a263b79-xs.png",
        "modo": "manter",
        "dataInicial": "N/A",
        "dataFinal": "5/6/2025",
        "inscriçãoEscola": True,
        "inscriçãoAluno": False,
        "fundamental1": False,
        "fundamental2": True,
        "ensinoMedio": True,
        "livre": False,
        "ensinoSuperior": False
    }
}